/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type Legal = {
  _id: string
  _type: "legal"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
  content?: BlockContent
}

export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
      listItem?: "bullet" | "number"
      markDefs?: Array<{
        href?: string
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: "image"
      _key: string
    }
>

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type ManualReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "manual"
}

export type Manual = {
  _id: string
  _type: "manual"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  summary?: string
  thumbnail?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  author?: string
  body?: BlockContent
  relatedManuals?: Array<
    {
      _key: string
    } & ManualReference
  >
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type DestinationReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "destination"
}

export type RoutesConfig = {
  _id: string
  _type: "routesConfig"
  _createdAt: string
  _updatedAt: string
  _rev: string
  routes?: Array<{
    from?: DestinationReference
    to?: DestinationReference
    shipIconId?: string
    _key: string
  }>
}

export type Destination = {
  _id: string
  _type: "destination"
  _createdAt: string
  _updatedAt: string
  _rev: string
  code?: string
  name?: string
  latitude?: number
  longitude?: number
}

export type LegalReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "legal"
}

export type SiteConfig = {
  _id: string
  _type: "siteConfig"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  twitterImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  socialMedia?: Array<{
    platform?:
      | "linkedin"
      | "instagram"
      | "whatsapp"
      | "facebook"
      | "phone"
      | "email"
    url?: string
    label?: string
    contactText?: string
    _key: string
  }>
  footerLegalLinks?: Array<
    {
      _key: string
    } & LegalReference
  >
  heroVideoUrl?: string
  showRouteArcs?: boolean
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Legal
  | SanityImageAssetReference
  | BlockContent
  | Slug
  | ManualReference
  | Manual
  | SanityImageCrop
  | SanityImageHotspot
  | DestinationReference
  | RoutesConfig
  | Destination
  | LegalReference
  | SiteConfig
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: sanity/queries/destination/queries.ts
// Variable: DESTINATIONS_QUERY
// Query: *[_type == "destination"] | order(name asc) {    _id,    code,    name,    latitude,    longitude  }
export type DESTINATIONS_QUERY_RESULT = Array<{
  _id: string
  code: string | null
  name: string | null
  latitude: number | null
  longitude: number | null
}>

// Source: sanity/queries/legal/queries.ts
// Variable: LEGAL_DOCUMENTS_QUERY
// Query: *[_type == "legal" && defined(slug.current)] | order(_updatedAt desc) {    _id,    title,    slug,    description,    _createdAt,    _updatedAt  }
export type LEGAL_DOCUMENTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  description: string | null
  _createdAt: string
  _updatedAt: string
}>

// Source: sanity/queries/legal/queries.ts
// Variable: LEGAL_DOCUMENT_BY_SLUG_QUERY
// Query: *[_type == "legal" && slug.current == $slug][0] {    _id,    title,    slug,    description,    _createdAt,    _updatedAt,    content[]{      ...,      markDefs[]{        ...,      },      _type == "image" => {        _key,        _type,        alt,        asset->,        hotspot,        crop      }    }  }
export type LEGAL_DOCUMENT_BY_SLUG_QUERY_RESULT = {
  _id: string
  title: string | null
  slug: Slug | null
  description: string | null
  _createdAt: string
  _updatedAt: string
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: "span"
          _key: string
        }>
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal"
        listItem?: "bullet" | "number"
        markDefs: Array<{
          href?: string
          _type: "link"
          _key: string
        }> | null
        level?: number
        _type: "block"
        _key: string
      }
    | {
        asset: {
          _id: string
          _type: "sanity.imageAsset"
          _createdAt: string
          _updatedAt: string
          _rev: string
          originalFilename?: string
          label?: string
          title?: string
          description?: string
          altText?: string
          sha1hash?: string
          extension?: string
          mimeType?: string
          size?: number
          assetId?: string
          uploadId?: string
          path?: string
          url?: string
          metadata?: SanityImageMetadata
          source?: SanityAssetSourceData
        } | null
        media?: unknown
        hotspot: SanityImageHotspot | null
        crop: SanityImageCrop | null
        alt: string | null
        _type: "image"
        _key: string
        markDefs: null
      }
  > | null
} | null

// Source: sanity/queries/legal/queries.ts
// Variable: LEGAL_DOCUMENTS_SITEMAP_QUERY
// Query: *[_type == "legal" && defined(slug.current)] {    "slug": slug.current,    _updatedAt  }
export type LEGAL_DOCUMENTS_SITEMAP_QUERY_RESULT = Array<{
  slug: string | null
  _updatedAt: string
}>

// Source: sanity/queries/manual/queries.ts
// Variable: MANUALS_LIST_QUERY
// Query: *[_type == "manual" && defined(slug.current)] | order(_createdAt desc) {      _id,  title,  slug,  summary,  author,  thumbnail { asset->, alt, hotspot, crop },  _createdAt,  _updatedAt,  "plainBody": pt::text(body)  }
export type MANUALS_LIST_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  summary: string | null
  author: string | null
  thumbnail: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  } | null
  _createdAt: string
  _updatedAt: string
  plainBody: string
}>

// Source: sanity/queries/manual/queries.ts
// Variable: MANUALS_LATEST_QUERY
// Query: *[_type == "manual" && defined(slug.current)] | order(_createdAt desc) [0...5] {      _id,  title,  slug,  summary,  author,  thumbnail { asset->, alt, hotspot, crop },  _createdAt,  _updatedAt,  "plainBody": pt::text(body)  }
export type MANUALS_LATEST_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: Slug | null
  summary: string | null
  author: string | null
  thumbnail: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  } | null
  _createdAt: string
  _updatedAt: string
  plainBody: string
}>

// Source: sanity/queries/manual/queries.ts
// Variable: MANUAL_BY_SLUG_QUERY
// Query: *[_type == "manual" && slug.current == $slug][0] {    _id,    title,    slug,    summary,    author,    thumbnail { asset->, alt, hotspot, crop },    _createdAt,    _updatedAt,    "plainBody": pt::text(body),    body[]{      ...,      markDefs[]{        ...,      },      _type == "image" => {        _key,        _type,        alt,        asset->,        hotspot,        crop      }    },    relatedManuals[]->{      _id,      title,      slug,      summary,      author,      thumbnail { asset->, alt, hotspot, crop },      _createdAt,      "plainBody": pt::text(body)    }  }
export type MANUAL_BY_SLUG_QUERY_RESULT = {
  _id: string
  title: string | null
  slug: Slug | null
  summary: string | null
  author: string | null
  thumbnail: {
    asset: {
      _id: string
      _type: "sanity.imageAsset"
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    alt: string | null
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  } | null
  _createdAt: string
  _updatedAt: string
  plainBody: string
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: "span"
          _key: string
        }>
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal"
        listItem?: "bullet" | "number"
        markDefs: Array<{
          href?: string
          _type: "link"
          _key: string
        }> | null
        level?: number
        _type: "block"
        _key: string
      }
    | {
        asset: {
          _id: string
          _type: "sanity.imageAsset"
          _createdAt: string
          _updatedAt: string
          _rev: string
          originalFilename?: string
          label?: string
          title?: string
          description?: string
          altText?: string
          sha1hash?: string
          extension?: string
          mimeType?: string
          size?: number
          assetId?: string
          uploadId?: string
          path?: string
          url?: string
          metadata?: SanityImageMetadata
          source?: SanityAssetSourceData
        } | null
        media?: unknown
        hotspot: SanityImageHotspot | null
        crop: SanityImageCrop | null
        alt: string | null
        _type: "image"
        _key: string
        markDefs: null
      }
  > | null
  relatedManuals: Array<{
    _id: string
    title: string | null
    slug: Slug | null
    summary: string | null
    author: string | null
    thumbnail: {
      asset: {
        _id: string
        _type: "sanity.imageAsset"
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      alt: string | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
    } | null
    _createdAt: string
    plainBody: string
  }> | null
} | null

// Source: sanity/queries/manual/queries.ts
// Variable: MANUALS_SITEMAP_QUERY
// Query: *[_type == "manual" && defined(slug.current)] {    "slug": slug.current,    _updatedAt  }
export type MANUALS_SITEMAP_QUERY_RESULT = Array<{
  slug: string | null
  _updatedAt: string
}>

// Source: sanity/queries/routes-config/queries.ts
// Variable: ROUTES_CONFIG_QUERY
// Query: *[_type == "routesConfig"][0] {    _id,    routes[] {      _key,      from->{ _id },      to->{ _id },      shipIconId    }  }
export type ROUTES_CONFIG_QUERY_RESULT = {
  _id: string
  routes: Array<{
    _key: string
    from: {
      _id: string
    } | null
    to: {
      _id: string
    } | null
    shipIconId: string | null
  }> | null
} | null

// Source: sanity/queries/site-config/queries.ts
// Variable: SITE_CONFIG_QUERY
// Query: *[_id == "siteConfig"][0] {    _id,    title,    description,    ogImage { asset->, alt, hotspot, crop },    twitterImage { asset->, alt, hotspot, crop },    socialMedia[] { _key, platform, url, label, contactText },    heroVideoUrl,    showRouteArcs,    footerLegalLinks[]{      _key,      "legal": @->{        _id,        title,        slug,        description,        _updatedAt      }    }  }
export type SITE_CONFIG_QUERY_RESULT =
  | {
      _id: "siteConfig"
      title: null
      description: null
      ogImage: null
      twitterImage: null
      socialMedia: null
      heroVideoUrl: null
      showRouteArcs: null
      footerLegalLinks: null
    }
  | {
      _id: "siteConfig"
      title: string | null
      description: null
      ogImage: null
      twitterImage: null
      socialMedia: null
      heroVideoUrl: null
      showRouteArcs: null
      footerLegalLinks: null
    }
  | {
      _id: "siteConfig"
      title: string | null
      description: string | null
      ogImage: null
      twitterImage: null
      socialMedia: null
      heroVideoUrl: null
      showRouteArcs: null
      footerLegalLinks: null
    }
  | {
      _id: "siteConfig"
      title: string | null
      description: string | null
      ogImage: {
        asset: {
          _id: string
          _type: "sanity.imageAsset"
          _createdAt: string
          _updatedAt: string
          _rev: string
          originalFilename?: string
          label?: string
          title?: string
          description?: string
          altText?: string
          sha1hash?: string
          extension?: string
          mimeType?: string
          size?: number
          assetId?: string
          uploadId?: string
          path?: string
          url?: string
          metadata?: SanityImageMetadata
          source?: SanityAssetSourceData
        } | null
        alt: string | null
        hotspot: SanityImageHotspot | null
        crop: SanityImageCrop | null
      } | null
      twitterImage: {
        asset: {
          _id: string
          _type: "sanity.imageAsset"
          _createdAt: string
          _updatedAt: string
          _rev: string
          originalFilename?: string
          label?: string
          title?: string
          description?: string
          altText?: string
          sha1hash?: string
          extension?: string
          mimeType?: string
          size?: number
          assetId?: string
          uploadId?: string
          path?: string
          url?: string
          metadata?: SanityImageMetadata
          source?: SanityAssetSourceData
        } | null
        alt: string | null
        hotspot: SanityImageHotspot | null
        crop: SanityImageCrop | null
      } | null
      socialMedia: Array<{
        _key: string
        platform:
          | "email"
          | "facebook"
          | "instagram"
          | "linkedin"
          | "phone"
          | "whatsapp"
          | null
        url: string | null
        label: string | null
        contactText: string | null
      }> | null
      heroVideoUrl: string | null
      showRouteArcs: boolean | null
      footerLegalLinks: Array<{
        _key: string
        legal: {
          _id: string
          title: string | null
          slug: Slug | null
          description: string | null
          _updatedAt: string
        }
      }> | null
    }
  | null

// Query TypeMap
import "@sanity/client"
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "destination"] | order(name asc) {\n    _id,\n    code,\n    name,\n    latitude,\n    longitude\n  }\n': DESTINATIONS_QUERY_RESULT
    '\n  *[_type == "legal" && defined(slug.current)] | order(_updatedAt desc) {\n    _id,\n    title,\n    slug,\n    description,\n    _createdAt,\n    _updatedAt\n  }\n': LEGAL_DOCUMENTS_QUERY_RESULT
    '\n  *[_type == "legal" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    description,\n    _createdAt,\n    _updatedAt,\n    content[]{\n      ...,\n      markDefs[]{\n        ...,\n      },\n      _type == "image" => {\n        _key,\n        _type,\n        alt,\n        asset->,\n        hotspot,\n        crop\n      }\n    }\n  }\n': LEGAL_DOCUMENT_BY_SLUG_QUERY_RESULT
    '\n  *[_type == "legal" && defined(slug.current)] {\n    "slug": slug.current,\n    _updatedAt\n  }\n': LEGAL_DOCUMENTS_SITEMAP_QUERY_RESULT
    '\n  *[_type == "manual" && defined(slug.current)] | order(_createdAt desc) {\n    \n  _id,\n  title,\n  slug,\n  summary,\n  author,\n  thumbnail { asset->, alt, hotspot, crop },\n  _createdAt,\n  _updatedAt,\n  "plainBody": pt::text(body)\n\n  }\n': MANUALS_LIST_QUERY_RESULT
    '\n  *[_type == "manual" && defined(slug.current)] | order(_createdAt desc) [0...5] {\n    \n  _id,\n  title,\n  slug,\n  summary,\n  author,\n  thumbnail { asset->, alt, hotspot, crop },\n  _createdAt,\n  _updatedAt,\n  "plainBody": pt::text(body)\n\n  }\n': MANUALS_LATEST_QUERY_RESULT
    '\n  *[_type == "manual" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    summary,\n    author,\n    thumbnail { asset->, alt, hotspot, crop },\n    _createdAt,\n    _updatedAt,\n    "plainBody": pt::text(body),\n    body[]{\n      ...,\n      markDefs[]{\n        ...,\n      },\n      _type == "image" => {\n        _key,\n        _type,\n        alt,\n        asset->,\n        hotspot,\n        crop\n      }\n    },\n    relatedManuals[]->{\n      _id,\n      title,\n      slug,\n      summary,\n      author,\n      thumbnail { asset->, alt, hotspot, crop },\n      _createdAt,\n      "plainBody": pt::text(body)\n    }\n  }\n': MANUAL_BY_SLUG_QUERY_RESULT
    '\n  *[_type == "manual" && defined(slug.current)] {\n    "slug": slug.current,\n    _updatedAt\n  }\n': MANUALS_SITEMAP_QUERY_RESULT
    '\n  *[_type == "routesConfig"][0] {\n    _id,\n    routes[] {\n      _key,\n      from->{ _id },\n      to->{ _id },\n      shipIconId\n    }\n  }\n': ROUTES_CONFIG_QUERY_RESULT
    '\n  *[_id == "siteConfig"][0] {\n    _id,\n    title,\n    description,\n    ogImage { asset->, alt, hotspot, crop },\n    twitterImage { asset->, alt, hotspot, crop },\n    socialMedia[] { _key, platform, url, label, contactText },\n    heroVideoUrl,\n    showRouteArcs,\n    footerLegalLinks[]{\n      _key,\n      "legal": @->{\n        _id,\n        title,\n        slug,\n        description,\n        _updatedAt\n      }\n    }\n  }\n': SITE_CONFIG_QUERY_RESULT
  }
}
