/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type DestinationReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "destination"
}

export type RoutesConfig = {
  _id: string
  _type: "routesConfig"
  _createdAt: string
  _updatedAt: string
  _rev: string
  routes?: Array<{
    from?: DestinationReference
    to?: DestinationReference
    shipIconId?: string
    _key: string
  }>
}

export type Destination = {
  _id: string
  _type: "destination"
  _createdAt: string
  _updatedAt: string
  _rev: string
  code?: string
  name?: string
  latitude?: number
  longitude?: number
}

export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type SiteConfig = {
  _id: string
  _type: "siteConfig"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  twitterImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  socialMedia?: Array<{
    platform?:
      | "linkedin"
      | "instagram"
      | "whatsapp"
      | "facebook"
      | "phone"
      | "email"
    url?: string
    label?: string
    contactText?: string
    _key: string
  }>
  heroVideoUrl?: string
  showRouteArcs?: boolean
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type AllSanitySchemaTypes =
  | DestinationReference
  | RoutesConfig
  | Destination
  | SanityImageAssetReference
  | SiteConfig
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug

// Source: sanity/queries/destination/queries.ts
// Variable: DESTINATIONS_QUERY
// Query: *[_type == "destination"] | order(name asc) {    _id,    code,    name,    latitude,    longitude  }
export type DESTINATIONS_QUERY_RESULT = Array<{
  _id: string
  code: string | null
  name: string | null
  latitude: number | null
  longitude: number | null
}>

// Source: sanity/queries/routes-config/queries.ts
// Variable: ROUTES_CONFIG_QUERY
// Query: *[_type == "routesConfig"][0] {    _id,    routes[] {      _key,      from->{ _id },      to->{ _id },      shipIconId    }  }
export type ROUTES_CONFIG_QUERY_RESULT = {
  _id: string
  routes: Array<{
    _key: string
    from: {
      _id: string
    } | null
    to: {
      _id: string
    } | null
    shipIconId: string | null
  }> | null
} | null

// Source: sanity/queries/site-config/queries.ts
// Variable: SITE_CONFIG_QUERY
// Query: *[_id == "siteConfig"][0] {    _id,    title,    description,    ogImage { asset->, alt, hotspot, crop },    twitterImage { asset->, alt, hotspot, crop },    socialMedia[] { _key, platform, url, label, contactText },    heroVideoUrl,    showRouteArcs  }
export type SITE_CONFIG_QUERY_RESULT =
  | {
      _id: "siteConfig"
      title: null
      description: null
      ogImage: null
      twitterImage: null
      socialMedia: null
      heroVideoUrl: null
      showRouteArcs: null
    }
  | {
      _id: "siteConfig"
      title: string | null
      description: string | null
      ogImage: null
      twitterImage: null
      socialMedia: null
      heroVideoUrl: null
      showRouteArcs: null
    }
  | {
      _id: "siteConfig"
      title: string | null
      description: string | null
      ogImage: {
        asset: {
          _id: string
          _type: "sanity.imageAsset"
          _createdAt: string
          _updatedAt: string
          _rev: string
          originalFilename?: string
          label?: string
          title?: string
          description?: string
          altText?: string
          sha1hash?: string
          extension?: string
          mimeType?: string
          size?: number
          assetId?: string
          uploadId?: string
          path?: string
          url?: string
          metadata?: SanityImageMetadata
          source?: SanityAssetSourceData
        } | null
        alt: string | null
        hotspot: SanityImageHotspot | null
        crop: SanityImageCrop | null
      } | null
      twitterImage: {
        asset: {
          _id: string
          _type: "sanity.imageAsset"
          _createdAt: string
          _updatedAt: string
          _rev: string
          originalFilename?: string
          label?: string
          title?: string
          description?: string
          altText?: string
          sha1hash?: string
          extension?: string
          mimeType?: string
          size?: number
          assetId?: string
          uploadId?: string
          path?: string
          url?: string
          metadata?: SanityImageMetadata
          source?: SanityAssetSourceData
        } | null
        alt: string | null
        hotspot: SanityImageHotspot | null
        crop: SanityImageCrop | null
      } | null
      socialMedia: Array<{
        _key: string
        platform:
          | "email"
          | "facebook"
          | "instagram"
          | "linkedin"
          | "phone"
          | "whatsapp"
          | null
        url: string | null
        label: string | null
        contactText: string | null
      }> | null
      heroVideoUrl: string | null
      showRouteArcs: boolean | null
    }
  | null

// Query TypeMap
import "@sanity/client"
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "destination"] | order(name asc) {\n    _id,\n    code,\n    name,\n    latitude,\n    longitude\n  }\n': DESTINATIONS_QUERY_RESULT
    '\n  *[_type == "routesConfig"][0] {\n    _id,\n    routes[] {\n      _key,\n      from->{ _id },\n      to->{ _id },\n      shipIconId\n    }\n  }\n': ROUTES_CONFIG_QUERY_RESULT
    '\n  *[_id == "siteConfig"][0] {\n    _id,\n    title,\n    description,\n    ogImage { asset->, alt, hotspot, crop },\n    twitterImage { asset->, alt, hotspot, crop },\n    socialMedia[] { _key, platform, url, label, contactText },\n    heroVideoUrl,\n    showRouteArcs\n  }\n': SITE_CONFIG_QUERY_RESULT
  }
}
